### ISSUE TITLE
Changes font

### ISSUE THREAD

**Issue by romanskorobagatko** [xhuajin/obsidian-carousel#1]
It changes font when enabling a plugin. I installed it via BRAT plugin, if it helps.

Here is a video: https://www.dropbox.com/scl/fi/yeizyi51wsrqdkspl2rjg/Screen_Recording_2024_10_01_14_25_13.mp4?rlkey=ld9xa9i60xqlfzp21izhg080x&raw=1

**Comment by xhuajin** [comment]
Thank you for your feedback. This issue has been fixed in version 1.0.1. Feel free to give it a try.
